name: generate animation

on:
  # executa automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"

  # permite executar manualmente
  workflow_dispatch:

  # executa a cada push na branch master
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # gera a animação da cobrinha com base nos commits do usuário
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: lpmtm
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # envia os arquivos gerados para a branch "output"
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
